<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta charset="utf-8" />
        <title>UMB-Fisio-Web</title>

        <meta name="description" content="User login page" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

        <!-- bootstrap & fontawesome -->
        <? echo Tag::css('ace/bootstrap') ?>
        <? echo Tag::css('ace/font-awesome') ?>

        <!-- text fonts -->
        <? echo Tag::css('ace/ace-fonts') ?>

        <!-- ace styles -->
        <? echo Tag::css("ace/ace") ?>

        <!--[if lte IE 9]>
                <link rel="stylesheet" href="../assets/css/ace-part2.css" />
        <![endif]-->
        <link rel="stylesheet" href="../assets/css/ace-rtl.css" />

        <!--[if lte IE 9]>
          <link rel="stylesheet" href="../assets/css/ace-ie.css" />
        <![endif]-->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

        <!--[if lt IE 9]>
        <script src="../assets/js/html5shiv.js"></script>
        <script src="../assets/js/respond.js"></script>
        <![endif]-->
        <? echo Html::includeCss() ?>
    </head>

    <body class="login-layout">
        <div class="main-container">
            <div class="main-content">
                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1">
                        <div class="login-container">
                            <div class="center">
                                <? echo Html::img("Escudo_UMB.png", "logoumb", "width=50%;height=50%") ?>
                            </div>

                            <div class="space-6"></div>

                           <?echo View::content()?>

                        </div>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.main-content -->
        </div><!-- /.main-container -->

        <!-- basic scripts -->

        <!--[if !IE]> -->
        <? echo Tag::js('ace/jquery') ?>

        <!-- <![endif]-->

        <!--[if IE]>
<script type="text/javascript">
window.jQuery || document.write("<script src='../assets/js/jquery1x.js'>"+"<"+"/script>");
</script>
<![endif]-->
        <script type="text/javascript">
            if ('ontouchstart' in document.documentElement)
<? echo Tag::js('ace/jquery.mobile.custom') ?>
        </script>

        <? echo Tag::js('ace/bootstrap') ?>
<!-- inline scripts related to this page -->
       
    </body>
</html>

