<?echo Form::open()?>
<div class="position-relative">
    <div id="login-box" class="login-box visible widget-box no-border">
        <div class="widget-body">
            <div class="widget-main">
                <h4 class="header blue lighter bigger">
                    <i class="ace-icon fa fa-coffee green"></i>
                    Ingrese su información
                </h4>

                <div class="space-6"></div>

                <form>
                    <fieldset>
                        <label class="block clearfix">
                            <span class="block input-icon input-icon-right">


                                <? echo Form::input("text", "cedula", "class='form-control' placeholder='Cedula'") ?>

                                <i class="ace-icon fa fa-user"></i>
                            </span>
                        </label>

                        <label class="block clearfix">
                            <span class="block input-icon input-icon-right">
                                <? echo Form::pass("clave", "class='form-control' placeholder='Clave'") ?>
                                <i class="ace-icon fa fa-lock"></i>
                            </span>
                        </label>

                        <div class="space"></div>

                        <div class="clearfix">
                            <label class="inline">

                                <span class="lbl"> </span>
                            </label>


                            <? echo Form::submit("Entrar", "class='width-35 pull-right btn btn-sm btn-primary' ") ?>


                        </div>

                        <div class="space-4"></div>
                    </fieldset>
                </form>


            </div><!-- /.widget-main -->


        </div><!-- /.widget-body -->
    </div><!-- /.login-box -->

</div><!-- /.position-relative -->
<?echo Form::close()?>