
<? View::content() ?>

<? echo Form::open("diagnostico/nuevo/$idhistoria/$iddicom/$idjpg") ?>
<? echo Form::hidden("oculto") ?>
<div class="row">
    <div class="col-xs-12 col-lg-6">
        <?
        $dicomfile = new Archivo();
        $dicomfile->find_first($iddicom);
        echo Html::imgUploadedFiles($dicomfile->nombre, "Imagen dicom", "width=50% height=50%")
        ?>


    </div>
    <div class="col-xs-12 col-lg-6">
        <?
        $jpgfile = new Archivo();
        $jpgfile->find_first($idjpg);
        echo Html::imgUploadedFiles($jpgfile->nombre, "Imagen dicom", "width=50% height=50%")
        ?>


    </div>
</div>

<div class="center"><legend><h1>Diagnóstico</h1></legend></div>
<br>
<div class="row">
    <!-- apartado B!-->
    <div class="text-primary"><h2>Apartado A</h2></div>
    <div><h3>Pregunta: ¿Cuánto dolor tiene?</h3></div>
    <div class="form-group">
        <label>1. Al andar en terreno llano</label>
        <? echo Form::dbSelect("diagnostico.ap_a_1", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <div class="form-group">
        <label>2. Al subir y bajar escaleras</label>
        <? echo Form::dbSelect("diagnostico.ap_a_2", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <div class="form-group">
        <label>3. Por la noche en la cama</label>
        <? echo Form::dbSelect("diagnostico.ap_a_3", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <div class="form-group">
        <label>4. Al estar sentado o tumbado</label>
        <? echo Form::dbSelect("diagnostico.ap_a_4", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <div class="form-group">
        <label>5. Al estar de pie</label>
        <? echo Form::dbSelect("diagnostico.ap_a_5", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <!-- apartado B!-->
    <div class="text-primary"><h2>Apartado B</h2></div>
    <div class="form-group">
        <label>1. ¿Cuánta rigidez nota después de despetarse por la mañana?</label>
        <? echo Form::dbSelect("diagnostico.ap_b_1", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
     <div class="form-group">
        <label>2. ¿Cuánta rigidez nota durante el resto del día después de estar sentado, tumbado o descansando?</label>
        <? echo Form::dbSelect("diagnostico.ap_b_2", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    
    <!-- apartado C!-->
    <div class="text-primary"><h2>Apartado C</h2></div>
    <div><h3>Pregunta: ¿Qué grado de dificultad tiene al...?</h3></div>
     <div class="form-group">
        <label>1. Bajar escaleras</label>
        <? echo Form::dbSelect("diagnostico.ap_c_1", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <div class="form-group">
        <label>2. Subir escaleras</label>
        <? echo Form::dbSelect("diagnostico.ap_c_2", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <div class="form-group">
        <label>3. Levantarse después de estar sentado</label>
        <? echo Form::dbSelect("diagnostico.ap_c_3", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <div class="form-group">
        <label>4. Estar de pie</label>
        <? echo Form::dbSelect("diagnostico.ap_c_4", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
     <div class="form-group">
        <label>5. Agacharse para coger algo del suelo</label>
        <? echo Form::dbSelect("diagnostico.ap_c_5", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
     <div class="form-group">
        <label>6. Andar por un terreno llano</label>
        <? echo Form::dbSelect("diagnostico.ap_c_6", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
     <div class="form-group">
        <label>7. Entrar y salir de un coche</label>
        <? echo Form::dbSelect("diagnostico.ap_c_7", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <div class="form-group">
        <label>8. Ir de compras</label>
        <? echo Form::dbSelect("diagnostico.ap_c_8", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <div class="form-group">
        <label>9. Ponerse las medias y los calcetines</label>
        <? echo Form::dbSelect("diagnostico.ap_c_9", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <div class="form-group">
        <label>10. Levantarse de la cama</label>
        <? echo Form::dbSelect("diagnostico.ap_c_10", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <div class="form-group">
        <label>11. Quitarse las medias o los calcetines</label>
        <? echo Form::dbSelect("diagnostico.ap_c_11", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <div class="form-group">
        <label>12. Estar tumbado en la cama</label>
        <? echo Form::dbSelect("diagnostico.ap_c_12", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <div class="form-group">
        <label>13. Entrar y salir de la ducha/bañera</label>
        <? echo Form::dbSelect("diagnostico.ap_c_13", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <div class="form-group">
        <label>14. Estar sentado</label>
        <? echo Form::dbSelect("diagnostico.ap_c_14", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    <div class="form-group">
        <label>15. Sentarse y levantarse del retrete</label>
        <? echo Form::dbSelect("diagnostico.ap_c_15", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
      <div class="form-group">
        <label>16. Hacer tareas domésticas pesadas</label>
        <? echo Form::dbSelect("diagnostico.ap_c_16", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
     <div class="form-group">
        <label>17. Hacer tareas domésticas ligeras</label>
        <? echo Form::dbSelect("diagnostico.ap_c_17", "nombre", array("tipodolor", "find"), null, "class='form-control'", null) ?>
    </div>
    
    
</div>


<div class="row">
    <div class="form-group">
        <label>Descripción del diagnóstico</label>
        <? echo Form::textarea("descripcion", "class='form-control'", "") ?>
    </div>
    <? echo Form::submit("Guardar", "class='btn btn-danger btn-sm'") ?>
</div>

<?
echo Form::close()?>