<div class="page-header">
    <h1>Terapias</h1>
</div>
<? echo View::content() ?>


<br>
<? echo Html::link("terapia/nuevo/$iddiagnostico", "Crear nuevo", "class='btn btn-danger btn-sm'") ?>
<? echo Html::link("diagnostico/index/$idhis", "Cancelar")?>
<br>
<br>
<? View::partial('paginators/extended', false, array('page' => $arrTerapias, 'url' => "terapia/index/$iddiagnostico")); ?>
<br>

<table class="table table-striped">
    <thead><tr style="text-align:center;font-weight:bold;">
            <th>Id terapia</th>
            <th>Fecha terapia</th>
            <th>Realizada</th>
            <th>Opciones</th>
           
        </tr></thead>   

    <tbody>
        <? foreach ($arrTerapias->items as $obj) { ?>
            <tr>
                <td><? echo $obj->id ?></td>
                <td><? echo $obj->fecha_terapia ?></td>
                <td><? 
                        if($obj->realizada_completa=="1"){
                            echo "SI";
                        }
                        else{
                            echo "NO";
                        }
                    ?></td>
                <td>
                    <div class="hidden-sm hidden-xs btn-group">
                        <!--<button class="btn btn-xs btn-success">
                           
                            <i class="ace-icon fa fa-check bigger-120"></i>
                            
                       </button>-->

                        <div class="btn btn-xs btn-info">

                            <? echo Html::linkSoloIcono("ace-icon fa fa-pencil bigger-120", "", false, "terapia/editar/$obj->id") ?>
                        </div>

                        <div class="btn btn-xs btn-danger">

                            <? echo Js::linkAction("eliminar/$obj->id", "", "¿Está seguro de eliminar?", "ace-icon fa fa-trash-o bigger-120") ?>
                        </div>
                       
                        <!--<button class="btn btn-xs btn-warning">
                            <i class="ace-icon fa fa-flag bigger-120"></i>
                        </button>-->
                    </div>

                    <div class="hidden-md hidden-lg">
                        <div class="inline pos-rel">
                            <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
                                <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                            </button>

                            <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                <li>
                                    <? echo "hola" ?>

                                </li>

                                <li>
                                    <a href="#" class="tooltip-success" data-rel="tooltip" title="Edit">
                                        <span class="green">
                                            <i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
                                        </span>
                                    </a>
                                </li>

                                <li>
                                    <a href="#" class="tooltip-error" data-rel="tooltip" title="Delete">
                                        <span class="red">
                                            <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                        </span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </td>
            </tr>
        <? } ?> 
    </tbody>
   
</table> 

<? View::partial('paginators/extended', false, array('page' => $arrTerapias,'url' => "terapia/index/$iddiagnostico")); ?>

