<div class="center">Docentes de la Universidad Movilizados</div>
<div class="center">Programa: psicología</div>

<br>

<div class="center">
    
        <div class="row">
            <div class="col-xs-1">Semestre</div>
            <div class="col-xs-2"><? echo Form::dbSelect("Tiposemestre_id")?></div>
            <div class="col-xs-1"><?echo Form::button("Consultar")?></div>
            <div class="col-xs-2"><?echo Html::link("movdocentesext/nuevo", "Crear nuevo")?></div>
            <div class="col-xs-6"></div>
        </div>
        
    
    
</div>
    
<table id="grid-basic" class="table table-condensed table-hover table-striped">
    <thead>
        <tr>
            <th data-column-id="id" data-type="numeric">ID</th>
            <th data-column-id="sender">Sender</th>
            <th data-column-id="received" data-order="desc">Received</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>10238</td>
            <td>eduardo@pingpong.com</td>
            <td>14.10.2013</td>
        </tr>
         <tr>
            <td>10238</td>
            <td>eduardo@pingpong.com</td>
            <td>14.10.2013</td>
        </tr>
         <tr>
            <td>10238</td>
            <td>eduardo@pingpong.com</td>
            <td>14.10.2013</td>
        </tr>
         <tr>
            <td>10238</td>
            <td>eduardo@pingpong.com</td>
            <td>14.10.2013</td>
        </tr>
         <tr>
            <td>10238</td>
            <td>eduardo@pingpong.com</td>
            <td>14.10.2013</td>
        </tr>
    </tbody>
</table>

<script>
    window.onload = function(){        
        
        $("#grid-basic").bootgrid();
    }
</script>